base_model: NousResearch/Llama-2-7b-hf
base_model_config: NousResearch/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: LDJnr/Puffin
    type: sharegpt:chat
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
max_packed_sequence_len:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.00
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_watch:
wandb_log_model:

data_seed: 42
seed: 42

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 7
optimizer: adamw_bnb_8bit
learning_rate: 0.00002
lr_scheduler: constant_with_warmup

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience: 5
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: false
flash_attention: true

save_strategy: epoch
eval_strategy: epoch
eval_steps: 0.2
save_steps: 0.2
save_total_limit: 5
load_best_model_at_end: true
greater_is_better: false
metric_for_best_model: eval_loss

debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
